# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-12 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='firstColor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='secondColor',
        ),
    ]
