# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180812_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='machineBadPoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='machineGoodPoint',
            field=models.IntegerField(default=0),
        ),
    ]
